version: 2
updates:
  - package-ecosystem: "github-actions"
    directories:
      - "/.github/workflows"
      - "/download-pyodide"
      - "/install-browser"
    schedule:
      interval: "monthly"
