name: "Install browser"
description: "Install a browser to run Pyodide tests"
inputs:
  runner:
    required: false
    type: string
    default: "selenium"
  browser:
    required: false
    type: string
    default: "chrome"
  browser-version:
    required: false
    type: string
    default: "latest"
  driver-version:
    required: false
    type: string
    default: "latest"
  playwright-version:
    required: false
    type: string
    default: ""
  python-executable:
    required: false
    type: string
    default: "python"
  github-token:
    description: "Github token to download drivers from Github releases"
    type: string
    required: false
    default: ""
runs:
  using: "composite"
  steps:
    - name: Install node
      uses: actions/setup-node@v3
      if: ${{ contains(inputs.browser, 'node') || inputs.runner == 'playwright' }}
      with:
        node-version: ${{ inputs.driver-version }}

    - name: Cache Playwright browsers
      uses: actions/cache@v3
      if: ${{ inputs.runner == 'playwright' }}
      with:
        path: .cache/ms-playwright
        key: ${{ runner.os }}-playwright-latest

    - name: Install playwright
      shell: bash -l {0}
      if: ${{ inputs.runner == 'playwright' }}
      run: |
        if [ -n "${{ inputs.playwright-version }}" ]
        then
          ${{ inputs.python-executable }} -m pip install playwright==${{inputs.playwright-version}}
        else
          ${{ inputs.python-executable }} -m pip install playwright
        fi
        # TODO: install only browsers that are required
        ${{ inputs.python-executable }} -m playwright install --with-deps
    - name: Install firefox
      uses: browser-actions/setup-firefox@latest
      if: ${{ inputs.runner == 'selenium' && contains(inputs.browser, 'firefox') }}
      with:
        firefox-version: ${{ inputs.browser-version }}

    - name: Install geckodriver
      uses: browser-actions/setup-geckodriver@latest
      if: ${{ inputs.runner == 'selenium' && contains(inputs.browser, 'firefox') }}
      with:
        geckodriver-version: ${{ inputs.driver-version }}
        token: ${{ inputs.github-token }}

    - name: Install chrome
      uses: browser-actions/setup-chrome@latest
      if: ${{ inputs.runner == 'selenium' && contains(inputs.browser, 'chrome') }}
      with:
        chrome-version: ${{ inputs.browser-version }}

    - name: Install chromedriver
      if: ${{ inputs.runner == 'selenium' && contains(inputs.browser, 'chrome') }}
      uses: nanasess/setup-chromedriver@v2

    - name: Enable Safari Driver
      shell: bash -l {0}
      if: ${{ inputs.runner == 'selenium' && contains(inputs.browser, 'safari') && contains(runner.os, 'macos') }}
      run: |
        sudo safaridriver --enable
